### ISSUE TITLE
CollectionView events and selection behaviours are not working properly on iOS

### ISSUE THREAD

**Issue by jpacov** [galadril/Xam.Plugin.SimpleBottomDrawer#5]
For CollectionView items placed inside Drawer, the events related to Selection are not working properly on iOS.
If I cut and paste my CollectionView code outside the drawer, they work properly.

Items in CollectionView are displayed correctly, but cannot be selected properly (selection flashed for a quick moment) and events related to it, either events itself of binded Commands are not fired.

In Android they work very well, the problem is only on iOS.

Using:
- VS2019. 
- Xamarin iOS v13.18.2.1.
- Xamarin Forms v4.7.0.1142

Please let me know if you find a workaround. 
Here the test code:

                <BottomDrawercontrol:BottomDrawer
                Padding="0"
                BackgroundColor="{StaticResource FoodLibraryBackgroundColor}"
                RelativeLayout.HeightConstraint="{ConstraintExpression Type=RelativeToParent,
                                                                       Property=Height,
                                                                       Factor=1,
                                                                       Constant=0}"
                RelativeLayout.WidthConstraint="{ConstraintExpression Type=RelativeToParent,
                                                                      Property=Width,
                                                                      Factor=1,
                                                                      Constant=0}"
                RelativeLayout.YConstraint="{ConstraintExpression Type=RelativeToParent,
                                                                  Property=Height,
                                                                  Factor=1,
                                                                  Constant=-35}">

                <StackLayout
                    Spacing="3"
                    Padding="18,0">

                    

                    <BoxView
                    Margin="20,16"
                    BackgroundColor="Gray"
                    CornerRadius="5"
                    HeightRequest="3"
                    HorizontalOptions="Center"
                    WidthRequest="80" />

                    <CollectionView
                            ItemsSource="{Binding DayMeals}"
                            Margin="10"
                            ItemTemplate="{StaticResource MealCardSelector}"
                            SelectionMode="Single"
                            SelectionChanged="CollectionView_SelectionChanged">
                        <CollectionView.ItemsLayout>
                            <LinearItemsLayout Orientation="Vertical"/>
                        </CollectionView.ItemsLayout>
                    </CollectionView>

                </StackLayout>

            </BottomDrawercontrol:BottomDrawer>

**Comment by galadril** [comment]
you could try to set InputTransparent="true", maybe on the SlackLayout or BottomDrawer

**Comment by jpacov** [comment]
Mmm...

When setting InputTransparent=true for the StackLayout, all controls in it do not react to gestures (I would say is the expected); but I need the CollectionView items to be selectable.

When setting InputTransparent=true to the whole drawer, is even worse :( , I can't even pull the drawer or click it to be shown.

:(

**Comment by jpacov** [comment]
Hi @galadril . 

By using Gesture recognizers instead of the Selected events and commands for the CollectionView, I was able to make it work.
For now, it's a workaround :)

**Comment by galadril** [comment]
Thanks, ill accept PR's if you find the issue ;)
